### PR TITLE
feat: react-native-image-picker fixed on M1 and Android !223929

### PR DESCRIPTION
**Pull request by alexandrius**
Thanks for submitting a PR! Please read these instructions carefully:

## Motivation (required)
Fixes newer Android versions' support
Fixes M1 macOS build

### CODE REVIEW

**Review by andrejborstnik — APPROVED** [review]
utACK

**Comment by andrejborstnik** [comment]
Audited
```
react-native-image-picker 0.28.1 -> @exodus/react-native-image-picker 0.28.1-exodus.3 9237657a45e8ae7cccb1b768d1fc619eca7e7597
```

**Comment by mvayngrib** [comment]
@andrejborstnik if you have write access here, please merge

**Comment by alexandrius** [comment]
> @andrejborstnik if you have write access here, please merge

Added

**Comment by andrejborstnik** [comment]
Added `Exodus/devs` write access to the repo

**Comment by andrejborstnik** [comment]
~@alexandrius please commit the version bump that you used to publish~ nm, it is in this PR, missed it

**Pull request merged**
